### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [DavisC0801/mod_0_skills#1]
**Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub**

- [x] Did you name and structure your directories and files correctly?
- [x] Did you make one initial commit?
- [x] Did you push your initial commit to Github?

**Part II: Top Down Design**

- [x] Did you break down larger processes into multiple smaller layers? **Excellent work on this**
- [x] Did you add and commit your changes with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Part III: Classes in a System** 

- [x] Did you structure and name your directories and files correctly?
- [x] Did you correctly categorize attributes and methods for each class?
- [x] Did you correctly identify data types of attributes for each class?
- [x] Did you add and commit each set of changes separately with a properly formatted commit message?
- [x] Did you push your changes to Github?

**Assessment Results**
- [x] Pass
- [ ] Conditional pass
- [ ] Fail with recommend for Mod 0 repeat
